#!/usr/bin/env bash
# Handle subagent stop events (timeout, crash, completion)
# Receives event data via stdin as JSON

set -euo pipefail

LOG_DIR="${CLAUDE_PROJECT_ROOT:-.}/.claude/plugins/technical-director/logs"
DEVIATION_FILE="${CLAUDE_PROJECT_ROOT:-.}/.claude/plugins/technical-director/deviations/log.yaml"
mkdir -p "$LOG_DIR"
mkdir -p "$(dirname "$DEVIATION_FILE")"

LOG_FILE="$LOG_DIR/subagent-stop-$(date +%Y%m%d).log"

# Read stdin (event JSON)
INPUT=$(cat)

TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Extract relevant fields
AGENT_TYPE=$(echo "$INPUT" | jq -r '.agent_type // "unknown"' 2>/dev/null)
STOP_REASON=$(echo "$INPUT" | jq -r '.stop_reason // "unknown"' 2>/dev/null)
DURATION=$(echo "$INPUT" | jq -r '.duration_ms // 0' 2>/dev/null)

# Log the stop event
cat >> "$LOG_FILE" << EOF
---
timestamp: $TIMESTAMP
event: subagent_stop
agent_type: $AGENT_TYPE
stop_reason: $STOP_REASON
duration_ms: $DURATION
---
EOF

# Check for abnormal stop conditions
ABNORMAL=false
CONTEXT_MSG=""

case "$STOP_REASON" in
  "timeout")
    ABNORMAL=true
    CONTEXT_MSG="[ORCHESTRATOR] Subagent timed out after ${DURATION}ms. Consider decomposing task further."
    ;;
  "error"|"crash")
    ABNORMAL=true
    CONTEXT_MSG="[ORCHESTRATOR] Subagent crashed unexpectedly. Check logs for details."
    ;;
  "cancelled")
    CONTEXT_MSG="[ORCHESTRATOR] Subagent was cancelled."
    ;;
  "completed")
    # Normal completion, no special handling
    ;;
esac

# Log deviation if abnormal
if [ "$ABNORMAL" = "true" ]; then
  # Get next deviation ID
  if [ -f "$DEVIATION_FILE" ]; then
    LAST_ID=$(grep -o 'id: [0-9]*' "$DEVIATION_FILE" | tail -1 | grep -o '[0-9]*' || echo "0")
    NEXT_ID=$((LAST_ID + 1))
  else
    NEXT_ID=1
    echo "# Deviation Log" > "$DEVIATION_FILE"
    echo "# Auto-generated by hooks" >> "$DEVIATION_FILE"
    echo "" >> "$DEVIATION_FILE"
  fi

  cat >> "$DEVIATION_FILE" << EOF
- id: $NEXT_ID
  timestamp: $TIMESTAMP
  expected: "Subagent completes normally"
  actual: "Subagent stopped: $STOP_REASON after ${DURATION}ms"
  root_cause: subagent_failure
  fix: |
    If timeout: Task may be too complex, decompose further.
    If crash: Check subagent prompt for errors.
    If repeated: Investigate systematic issue.

EOF
fi

# Output context if there's something to report
if [ -n "$CONTEXT_MSG" ]; then
  cat << EOF
{
  "hookSpecificOutput": {
    "hookEventName": "SubagentStop",
    "additionalContext": "$CONTEXT_MSG"
  }
}
EOF
else
  echo '{}'
fi

exit 0
